disabled_rules:
  - function_parameter_count
  - identifier_name
  - line_length
  - statement_position

excluded:
  - Carthage
  - Pods
  - Example/Pods

colon:
  apply_to_dictionaries: false

type_name:
  excluded: Tests_StringTruncation
